font:
    size: 9
    normal:
        family: JetBrains Mono
    bold:
        family: JetBrains Mono
    italic:
        family: JetBrains Mono
    bold_italic:
        family: JetBrains Mono

colors:
    primary:
        background: "#262626"
