[custom0]
binding='<Shift><Super>s'
command='gnome-screenshot -ca'
name='Screeshot'

[custom1]
binding='<Super>e'
command='emacs'
name='Emacs'

[custom2]
binding='<Super>a'
command='emacs --eval "(artist-mode)"'
name='Emacs Artist Mode'

[custom3]
binding='<Super>d'
command='emacs .'
name='Dired'

[custom4]
binding='<Super>t'
command="emacs --eval '(ansi-term \"bash\")'"
name='Terminal'

[custom5]
binding='<Super>c'
command='emacs --eval "(progn (calc) (other-window 2) (delete-window))"'
name='Calc'

[custom6]
binding='<Super>h'
command='emacs --eval "(progn (proced) (delete-other-windows))"'
name='Proced'
